name: .NET CI

'on':
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Restore Web Solution
        run: dotnet restore eShop.Web.slnf

      - name: Build Web Solution
        run: dotnet build eShop.Web.slnf --configuration Release --no-restore

      - name: Test Unit Projects
        run: |
          dotnet test --project tests/Basket.UnitTests/Basket.UnitTests.csproj --configuration Release --no-build --no-progress --output detailed
          dotnet test --project tests/Ordering.UnitTests/Ordering.UnitTests.csproj --configuration Release --no-build --no-progress --output detailed