name: .NET CI

'on':
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Web Solution
        run: dotnet restore eShop.Web.slnf

      - name: Build Web Solution
        run: dotnet build eShop.Web.slnf --configuration Release --no-restore

      - name: Test
        run: dotnet test --solution eShop.Web.slnf --configuration Release --no-build --no-progress --output detailed